<?php

/**
 * @file
 * Hooks for Canvas Utilities Palettes.
 */

declare(strict_types=1);

use Drupal\Core\Url;

/**
 * Implements hook_page_attachments().
 *
 * @phpstan-param array<string, mixed> $attachments
 */
function canvas_utilities_palette_page_attachments(array &$attachments): void {
  $active_theme = \Drupal::theme()->getActiveTheme()->getName();
  $default_theme = (string) \Drupal::config('system.theme')->get('default');
  if ($active_theme !== $default_theme) {
    return;
  }
  $attachments['#attached']['html_head_link'][] = [[
    'rel' => 'stylesheet',
    'href' => Url::fromRoute('canvas_utilities_palette.asset', ['theme' => $default_theme])->toString(),
  ], TRUE,
  ];
  $attachments['#cache']['tags'][] = 'canvas_utilities_palette_list';
}
