<?php

declare(strict_types=1);

namespace Drupal\canvas_utilities_fonts\Controller;

use Drupal\canvas_utilities_fonts\Entity\FontFamily;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\File\FileUrlGeneratorInterface;
use Symfony\Component\HttpFoundation\Response;

/**
 * Serves local @font-face declarations.
 */
final class FontAssetController {

  /**
   * Constructs the font asset controller. */
  public function __construct(
    private readonly EntityTypeManagerInterface $entityTypeManager,
    private readonly FileUrlGeneratorInterface $fileUrlGenerator,
  ) {}

  /**
   * Returns compiled local-font CSS. */
  public function __invoke(string $theme): Response {
    $rules = [];
    foreach ($this->entityTypeManager->getStorage('canvas_utilities_font')->loadMultiple() as $entity) {
      if (!$entity instanceof FontFamily || !$entity->status() || $entity->getTheme() !== $theme || $entity->getProvider() !== 'local_file') {
        continue;
      }
      foreach ($entity->getFaces() as $face) {
        $url = $this->fileUrlGenerator->generateString($face['uri']);
        $family = str_replace(['\\', "'"], ['\\\\', "\\'"], $entity->getFamily());
        $rules[] = "@font-face {\n  font-family: '" . $family . "';\n  src: url('" . $url . "') format('" . $face['format'] . "');\n  font-weight: " . $face['weight'] . ";\n  font-style: " . $face['style'] . ";\n  font-display: swap;\n}";
      }
    }
    $css = "/* Generated by Canvas Utilities Fonts. */\n" . implode("\n\n", $rules) . "\n";
    $response = new Response($css, 200, ['Content-Type' => 'text/css; charset=UTF-8']);
    $response->setEtag(hash('sha256', $css));
    $response->setPublic();
    $response->setMaxAge(300);
    return $response;
  }

}
