<?php

declare(strict_types=1);

namespace Drupal\canvas_utilities_palette\Controller;

use Drupal\canvas_utilities_palette\Entity\Palette;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Symfony\Component\HttpFoundation\Response;

/**
 * Serves published palette custom properties.
 */
final class PaletteAssetController {

  /**
   * Constructs the palette asset controller. */
  public function __construct(private readonly EntityTypeManagerInterface $entityTypeManager) {}

  /**
   * Returns compiled palette CSS. */
  public function __invoke(string $theme): Response {
    $declarations = [];
    foreach ($this->entityTypeManager->getStorage('canvas_utilities_palette')->loadMultiple() as $entity) {
      if (!$entity instanceof Palette || !$entity->status() || $entity->getTheme() !== $theme) {
        continue;
      }
      foreach ($entity->getColors() as $color) {
        $declarations['--' . $entity->getPrefix() . '-' . $color['id']] = $color['value'];
      }
    }
    ksort($declarations);
    $lines = array_map(static fn (string $name, string $value): string => sprintf('  %s: %s;', $name, $value), array_keys($declarations), $declarations);
    $css = "/* Generated by Canvas Utilities Palettes. */\n" . ($lines === [] ? '' : ":root {\n" . implode("\n", $lines) . "\n}\n");
    $response = new Response($css, 200, ['Content-Type' => 'text/css; charset=UTF-8']);
    $response->setEtag(hash('sha256', $css));
    $response->setPublic();
    $response->setMaxAge(300);
    return $response;
  }

}
