<?php

declare(strict_types=1);

namespace Drupal\canvas_utilities_style_guide\StyleGuide;

use Drupal\canvas_utilities_style_guide\Entity\StyleGuideValues;
use Drupal\Core\Entity\EntityTypeManagerInterface;

/**
 * Compiles published style-guide overrides into deterministic CSS.
 */
final class StyleGuideCssCompiler {

  /**
   * Constructs a CSS compiler.
   */
  public function __construct(
    private readonly StyleGuideDiscovery $discovery,
    private readonly EntityTypeManagerInterface $entityTypeManager,
    private readonly StyleGuideValueValidator $valueValidator,
  ) {}

  /**
   * Compiles CSS for a theme.
   */
  public function compile(string $theme): string {
    $rules = [];
    $storage = $this->entityTypeManager->getStorage('canvas_utilities_sg_values');
    foreach ($this->discovery->getDefinitions($theme) as $guide_id => $definition) {
      $entity = $storage->load(StyleGuideRepository::entityId($theme, $guide_id));
      $values = $entity instanceof StyleGuideValues ? $entity->getValues() : [];
      foreach ($definition['contexts'] as $context_id => $context) {
        $declarations = [];
        foreach ($definition['groups'] as $group) {
          foreach ($group['controls'] as $control_id => $control) {
            if (!isset($control['targets'][$context_id])) {
              continue;
            }
            $value = $values[$control_id][$context_id] ?? $control['default'][$context_id] ?? NULL;
            if ($value === NULL) {
              continue;
            }
            $value = $this->valueValidator->toCssValue($control, $value);
            if ($value === '') {
              continue;
            }
            $property = $control['targets'][$context_id]['property'];
            $declarations[$property] = (string) $value;
          }
        }
        if ($declarations !== []) {
          ksort($declarations);
          $body = array_map(static fn (string $property, string $value): string => sprintf('  %s: %s;', $property, $value), array_keys($declarations), $declarations);
          $rules[] = $context['selector'] . " {\n" . implode("\n", $body) . "\n}";
        }
      }
    }
    return "/* Generated by Canvas Utilities. */\n" . implode("\n\n", $rules) . "\n";
  }

}
