<?php

declare(strict_types=1);

namespace Drupal\canvas_utilities_style_guide\GeneratedCss;

use Drupal\canvas_utilities\GeneratedCss\GeneratedCssProviderInterface;
use Drupal\canvas_utilities\GeneratedCss\GeneratedCssSource;
use Drupal\canvas_utilities_style_guide\StyleGuide\StyleGuideCssCompiler;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Extension\ExtensionPathResolver;

/**
 * Produces content-addressed Style Guide override CSS.
 */
final class StyleGuideGeneratedCssProvider implements GeneratedCssProviderInterface {

  /**
   * Constructs the Style Guide generated CSS provider.
   */
  public function __construct(
    private readonly StyleGuideCssCompiler $compiler,
    private readonly ExtensionPathResolver $extensionPathResolver,
  ) {}

  /**
   * {@inheritdoc}
   */
  public function id(): string {
    return 'style-guide';
  }

  /**
   * {@inheritdoc}
   */
  public function getLibrary(): string {
    return 'canvas_utilities_style_guide/override';
  }

  /**
   * {@inheritdoc}
   */
  public function getPlaceholderPath(): string {
    return $this->extensionPathResolver->getPath('module', 'canvas_utilities_style_guide') . '/css/generated-css-placeholder.css';
  }

  /**
   * {@inheritdoc}
   */
  public function getWeight(): int {
    return 0;
  }

  /**
   * {@inheritdoc}
   */
  public function build(string $theme): ?GeneratedCssSource {
    $css = $this->compiler->compile($theme);
    if (trim($css) === '/* Generated by Canvas Utilities. */') {
      return NULL;
    }
    return new GeneratedCssSource($css, $this->getCacheTags($theme));
  }

  /**
   * {@inheritdoc}
   */
  public function getCacheTags(string $theme): array {
    return [
      'config:canvas_utilities_sg_values_list',
      'config:canvas_utilities_sg_definition_list',
      'config:canvas_utilities_palette_list',
      'config:canvas_utilities_font_list',
      'config:core.extension',
      'config:system.theme',
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getAffectedThemes(EntityInterface $entity): array {
    if (!in_array($entity->getEntityTypeId(), [
      'canvas_utilities_sg_values',
      'canvas_utilities_sg_definition',
      'canvas_utilities_palette',
      'canvas_utilities_font',
    ], TRUE)) {
      return [];
    }
    $values = $entity->toArray();
    $theme = $values['theme'] ?? NULL;
    return is_string($theme) && preg_match('/^[a-z][a-z0-9_]*$/', $theme) ? [$theme] : [];
  }

}
